name: Version

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: gradle -v
      - run: mvn -version
      - run: pwd
      - run: ls -la
      - run: whoami
      - run: sudo apt update
      - run: sudo apt install inotify-tools
      - run: install inotify-tools
      - run: which inotifywait
      - run: where inotifywait
