name: Version

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: sudo apt update
      - run: sudo apt install inotify-tools
      - run: inotifywait -mr /home/runner --format '%T;%w;%f;%e' --timefmt %T -o /home/test.csv & echo "basak"
      - run: gradle -v
      - run: mvn -version
      - run: pwd
      - run: ls -la
      - run: ls -la /
      - run: ls -la /home
      - run: ls -la /home/runner
      - run: ls -la /home/runner/work
      - run: ls -la /home/runner/work/optimizing-ci-builds
      - run: ls -la /home/runner/work/optimizing-ci-builds/optimizing-ci-builds
      - run: whoami
      - run: cat /home/test.csv
